---
title: "Package Bendford Tests"
author: "David Jackson"
date: "11/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(scales)
library(dplyr)
library(readr)
library(BenfordTests)
```

### Set the random seed to an arbitrary number
* https://youtu.be/7uhAn19V1EY


```{r}
set.seed(421)
```

### Create a sample satisfying Benford's law

```{r}
X<-rbenf(n=20)
X
```

### Look at the first digits of the sample

```{r}
signifd(X)
```

### Perform a Chi-squared Test on the sample's first digits using defaults
```{r}
chisq.benftest(X)
```

### Plot histogram of first digit

```{r}
signifd.analysis(X)
```

### New York Times US COVID-19 Cases and Deaths


```{r}
df <- read.csv("../DATA/us.csv")
df$date <- as.Date(df$date)
Y <- diff(df$cases,lag=1)
Y <- subset(Y, Y >=0)
Z <- diff(df$deaths,lag=1)
Z <- subset(Y,Y>0)
```
```{r}
ggplot(df) + geom_line(aes(x=date,y=cases))
ggplot(df) + geom_line(aes(x=date,y=deaths))
```

#### first digits Cases

```{r}
YY <- signifd(Y)
YY <- subset(YY,YY >=0)
signifd.analysis(YY)

```

### first Digit Deaths

```{r}
ZZ<- signifd(Z)
ZZ <-subset(ZZ,ZZ>=0)
signifd.analysis(ZZ)
```


#### New York COVID-19 Deaths 

```{r}
nyt <- read_csv("../DATA/us-states.csv") %>% filter(state =="New York")

 NYTD<- diff(nyt$deaths,lag=1)

```
```{r}
NYTD <- signifd(NYTD)
NYTD <-subset(NYTD,NYTD>=0)
signifd.analysis(ZZ)
```

